spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/userService/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orderService/**
        - id: storage-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/storageService/**