server:
  port: 8081

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=api/users/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=api/orders/**
          - id: storage-service
            uri: lb://storage-service
            predicates:
              - Path=api/storage/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: debug