server:
  port: 0
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/orderDB?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        jdbc:
          batch_size: 50
        show_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: order-service
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate:
      SQL: DEBUG